Accept the sorted data.
Accept search value.
Middle value is is equal to addition of low index and high index and divide by 2.
After getting the mid value check whether the input(search value) is equal to the mid value.
  (if true return mid index otherwise jump to next cond).
If mid value of index is less than input it prints the mid value + 1 otherwise mid value - 1.
If cond is false Repeatedly check from the second point until the value is found.
